Repository AgentDock/AgentDock, pull requests merged in 2025-05, with the labels that each got.

#139 🔧 Fix minor localization issues and update broken file links in documentation
  docs/i18n/russian/README.md
  docs/i18n/ukrainian/README.md
Labels: documentation

#155 fix(layout): Correct docs sticky sidebar and mobile layout
  src/app/docs/docs.css
  src/app/docs/layout.tsx
  src/components/layout/layout-content.tsx
Labels: open source client

#156 feat(evaluation): Implement Phase 1 Evaluators and Runner
  .gitignore
  agentdock-core/package.json
  agentdock-core/pnpm-lock.yaml
  agentdock-core/src/evaluation/evaluators/index.ts
  agentdock-core/src/evaluation/evaluators/lexical/__tests__/keyword_coverage.test.ts
  agentdock-core/src/evaluation/evaluators/lexical/__tests__/sentiment.test.ts
  agentdock-core/src/evaluation/evaluators/lexical/__tests__/similarity.test.ts
  agentdock-core/src/evaluation/evaluators/lexical/__tests__/toxicity.test.ts
  agentdock-core/src/evaluation/evaluators/lexical/index.ts
  agentdock-core/src/evaluation/evaluators/lexical/keyword_coverage.ts
  agentdock-core/src/evaluation/evaluators/lexical/sentiment.ts
  agentdock-core/src/evaluation/evaluators/lexical/similarity.ts
  agentdock-core/src/evaluation/evaluators/lexical/toxicity.ts
  agentdock-core/src/evaluation/evaluators/llm/__tests__/judge.test.ts
  agentdock-core/src/evaluation/evaluators/llm/index.ts
  agentdock-core/src/evaluation/evaluators/llm/judge.ts
  agentdock-core/src/evaluation/evaluators/nlp/__tests__/accuracy.base.test.ts
  agentdock-core/src/evaluation/evaluators/nlp/__tests__/accuracy.config.test.ts
  agentdock-core/src/evaluation/evaluators/nlp/__tests__/accuracy.edge_cases.test.ts
  agentdock-core/src/evaluation/evaluators/nlp/__tests__/accuracy.errors.test.ts
  agentdock-core/src/evaluation/evaluators/nlp/__tests__/accuracy.inputs.test.ts
  agentdock-core/src/evaluation/evaluators/nlp/accuracy.ts
  agentdock-core/src/evaluation/evaluators/nlp/index.ts
  agentdock-core/src/evaluation/evaluators/rule-based/__tests__/evaluator.test.ts
  agentdock-core/src/evaluation/evaluators/rule-based/evaluator.ts
  agentdock-core/src/evaluation/evaluators/rule-based/index.ts
  agentdock-core/src/evaluation/evaluators/tool/__tests__/usage.test.ts
  agentdock-core/src/evaluation/evaluators/tool/index.ts
  agentdock-core/src/evaluation/evaluators/tool/usage.ts
  agentdock-core/src/evaluation/index.ts
  agentdock-core/src/evaluation/runner/__tests__/index.test.ts
  agentdock-core/src/evaluation/runner/index.ts
  agentdock-core/src/evaluation/storage/json_file_storage.ts
  agentdock-core/src/evaluation/types/index.ts
  agentdock-core/src/evaluation/utils/__tests__/input-text-extractor.test.ts
  agentdock-core/src/evaluation/utils/index.ts
  agentdock-core/src/evaluation/utils/input-text-extractor.ts
  agentdock-core/src/index.ts
  agentdock-core/src/llm/types.ts
  agentdock-core/src/types/string-comparisons.d.ts
  docs/evaluations/README.md
  docs/evaluations/custom-evaluators.md
  docs/evaluations/evaluators/keyword-coverage.md
  docs/evaluations/evaluators/lexical-evaluators.md
  docs/evaluations/evaluators/lexical-similarity.md
  docs/evaluations/evaluators/llm-judge.md
  docs/evaluations/evaluators/nlp-accuracy.md
  docs/evaluations/evaluators/rule-based.md
  docs/evaluations/evaluators/sentiment.md
  docs/evaluations/evaluators/tool-usage.md
  docs/evaluations/evaluators/toxicity.md
  docs/prd/evaluation-framework.md
  docs/roadmap/evaluation-framework.md
  jest.config.ts
  package.json
  pnpm-lock.yaml
  scripts/examples/run_evaluation_example.ts
  src/lib/docs-config.ts
  tests/jest.setup.ts
Labels: agentdock-core, test
